<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN " "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es"  lang="es">

<head>
  <title>Tesis - Israel Zun&ntilde;iga de la Mora</title>
  <meta name="description" content="Proyecto de Tesis de Israel Zuñiga - En el cual se diseña y construirá un Pico Satélite" />
  <meta name="keywords" content="universidad de colima, facultad de telematica, colima, mexico, cansat, cubesat, cansat, pico, nano, micro, femto, satelite, satellite, high altitude balloning, open source software, open source hardware" />
  <meta http-equiv="content-type" content="text/html; charset=charset=UTF-8" />
  <link rel="stylesheet" type="text/css" href="style/style.css" />
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-142084-5']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>

<body>
  <div id="main">
    <div id="links"></div>
    <div id="header">
      <div id="logo">
        <div id="logo_text">
          <!-- class="green", allows you to change the colour of the text - other classes are: "blue", "orange", "red", "purple" and "yellow" -->
          <h1>Israel <span class="green">Zu&ntilde;iga de la Mora</span></h1>
          <h2>"Dise&ntilde;o y Fabricaci&oacute;n De Un Pico-Sat&eacute;lite Artificial Mediante Las Normas Cansat"</h2>
        </div>
      </div>