<div class="sidebar">
  <!-- insert your sidebar items here -->
	<h1>Carta de Compromiso</h1>
	<p>Toda tesis formal, debe ser evaluada y avalada por asesores. <a href="img/carta.jpg" target="_blank">Esta es mi carta de compromiso.</a></p>
  <h1>Perfil y Academia</h1>
  <ul>
    <li><a href="http://www.ucol.mx/">Universidad de Colima</a></li>
    <li><a href="http://telematicanet.ucol.mx/">Facultad de Telem&aacute;tica</a></li>
    <li><a href="http://www.linkedin.com/pub/israel-zu%C3%B1iga-de-la-mora/b/793/2a">Mi perfil profesional en LinkedIn</a></li>
  </ul>
  <p>"It's like a real satellite except we build it in a Coke can" Robert J. Twiggs.</p>
</div>